//Do not edit this file. It is generated automatically.

using UiStateSmithy.Samples.States;

namespace UiStateSmithy.Samples {

    public partial class UiStateSwitcherSample {
        private void AddStates() {
            var initUiState = new InitUiState(this);
            InitialUiState = initUiState;
            
            var metaUiState = new MetaUiState(this);
            var shopUiState = new ShopUiState(this);
            var loadingUiState = new LoadingUiState(this);
        }
    }
}
